# Generated by Django 5.0.2 on 2024-03-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_verse', '0003_motos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('año', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Seminuevo', 'Seminuevo'), ('Usado', 'Usado')], max_length=30)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
