# Generated by Django 5.0.2 on 2024-03-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_verse', '0004_bicis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicis',
            name='estado',
        ),
    ]
